<?php

declare(strict_types=1);

namespace Sangezar\DockerClient\Exception\Validation;

/**
 * Exception thrown when a required parameter is missing
 */
class MissingRequiredParameterException extends ValidationException
{
    private string $parameterName;

    /**
     * @param string $parameterName Name of the missing parameter
     * @param string $message Additional message (automatically generated by default)
     * @param int $code Error code
     * @param \Throwable|null $previous Previous exception
     */
    public function __construct(
        string $parameterName,
        string $message = '',
        int $code = 0,
        ?\Throwable $previous = null
    ) {
        $this->parameterName = $parameterName;

        if (empty($message)) {
            $message = sprintf('Required parameter "%s" is missing', $parameterName);
        }

        parent::__construct($message, $code, $previous);
    }

    /**
     * Get the name of the missing parameter
     *
     * @return string
     */
    public function getParameterName(): string
    {
        return $this->parameterName;
    }
}
