<?php

declare(strict_types=1);

namespace Sangezar\DockerClient\Exception\Validation;

/**
 * Exception thrown when required conditions for an operation are not met
 */
class PreConditionFailedException extends ValidationException
{
    private string $operation;
    private ?string $resource;
    private ?string $condition;

    /**
     * @param string $operation Operation name
     * @param string|null $resource Resource name (optional)
     * @param string|null $condition Description of the unmet condition (optional)
     * @param string $message Additional message (automatically generated by default)
     * @param int $code Error code
     * @param \Throwable|null $previous Previous exception
     */
    public function __construct(
        string $operation,
        ?string $resource = null,
        ?string $condition = null,
        string $message = '',
        int $code = 0,
        ?\Throwable $previous = null
    ) {
        $this->operation = $operation;
        $this->resource = $resource;
        $this->condition = $condition;

        if (empty($message)) {
            $message = sprintf('Pre-condition failed for operation "%s"', $operation);

            if ($resource !== null) {
                $message .= sprintf(' on resource "%s"', $resource);
            }

            if ($condition !== null) {
                $message .= sprintf(': %s', $condition);
            }
        }

        parent::__construct($message, $code, $previous);
    }

    /**
     * Get the operation name
     *
     * @return string
     */
    public function getOperation(): string
    {
        return $this->operation;
    }

    /**
     * Get the resource name
     *
     * @return string|null
     */
    public function getResource(): ?string
    {
        return $this->resource;
    }

    /**
     * Get the condition description
     *
     * @return string|null
     */
    public function getCondition(): ?string
    {
        return $this->condition;
    }
}
